name: CI Quality Check
on: [push, pull_request]

jobs:
  check:
    runs-mode: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install
      - run: make check # Ruft direkt Type-Check, Linting & Tests auf!
